version: 1.18.0
files:
  - url: https://github.com/anetrebskii/notula-releases/releases/download/v1.18.0/Notula-Windows.exe
    sha512: Er725CODFoOPf6f0kixFPoe4CW2F7bhr2WePiy6N/jIG1l2WGEzGuqzCND3zi5EvtNo0T5I8h58g/OgMqWypDw==
    size: 205937091
  - url: https://github.com/anetrebskii/notula-releases/releases/download/v1.18.0/Notula-Windows-x64.exe
    sha512: tzW3jU5PlplWjGimBeqKXaX0wWc4uciD+yOFJbK0SBtNpzhoWcIwh+JsYS+ew8NhApoTeLXXBYOdCjh6DcL/uA==
    size: 106977346
  - url: https://github.com/anetrebskii/notula-releases/releases/download/v1.18.0/Notula-Windows-arm64.exe
    sha512: KwpvB4coj0+jgGEngi0omUVJ5HEfV1xNic3sgweraS0Wq/IVDXoSRecY/9M1NUoZngSD4oFPt0uyAP4Y2gMm4Q==
    size: 99562663
path: https://github.com/anetrebskii/notula-releases/releases/download/v1.18.0/Notula-Windows.exe
sha512: Er725CODFoOPf6f0kixFPoe4CW2F7bhr2WePiy6N/jIG1l2WGEzGuqzCND3zi5EvtNo0T5I8h58g/OgMqWypDw==
releaseDate: '2026-08-26T08:30:23.713Z'
