version: 1.16.0
files:
  - url: https://github.com/anetrebskii/notula-releases/releases/download/v1.16.0/Notula-Windows.exe
    sha512: W8dDhtBujnP+brC+fZ51tzKNVQuJ1Qxi+Jh5zas2kENMR4pC7CQ+aHjiMs+S6+pdLEjCoNT2ZQGnDO8suOnEYQ==
    size: 205173796
  - url: https://github.com/anetrebskii/notula-releases/releases/download/v1.16.0/Notula-Windows-x64.exe
    sha512: 3NBSKcbiFcWloVGftz5PmoEgB2FQTL10L+Kxd9wOw2Pygx/7cC8jUwCSmEyCxpOy3LwpM/DMdrfsyeLeRbQuug==
    size: 106595794
  - url: https://github.com/anetrebskii/notula-releases/releases/download/v1.16.0/Notula-Windows-arm64.exe
    sha512: Qg+Z9uBUPZ4R8WHJPsJp9+Hq3uUgbZKzQIbwEHlkDg4julYyZLTaEXCngC6F9MUU4rLofJUaR10TnETUja7Jjg==
    size: 99181004
path: https://github.com/anetrebskii/notula-releases/releases/download/v1.16.0/Notula-Windows.exe
sha512: W8dDhtBujnP+brC+fZ51tzKNVQuJ1Qxi+Jh5zas2kENMR4pC7CQ+aHjiMs+S6+pdLEjCoNT2ZQGnDO8suOnEYQ==
releaseDate: '2026-08-24T13:55:45.961Z'
